Feature/drac 73/edit account
menklab/dracarys-frontend pull request #18
Opened 2023-01-19 11:51 UTC by MizhgunMenk

2023-01-19 12:33 UTC, shimevaily commented on adapters/account/deleteAccountElement.ts
> +  const res = await fetch(API_ROUTES.ACCOUNTS_ELEMENTS() + `/${String(elementId)}`, {
there is no need to wrap number in String since you're using template literals

2023-01-19 12:33 UTC, shimevaily commented on adapters/account/getAccount.ts
> +  const res = await fetch(API_ROUTES.ACCOUNTS() + `/${String(accountId)}`, {
same here

2023-01-19 12:34 UTC, shimevaily commented on adapters/account/getAccount.ts
> +  return data || {};
why are you using object if return needs an array?

2023-01-19 12:34 UTC, shimevaily commented on adapters/account/getAccountElements.ts
> +  const res = await fetch(API_ROUTES.ACCOUNTS_ELEMENTS() + `/?accountId=${String(accountId)}`, {
same here

2023-01-19 12:35 UTC, shimevaily commented on adapters/account/updateAccount.ts
> +  const res = await fetch(API_ROUTES.ACCOUNTS() + `/${String(accountId)}`, {
same here

2023-01-19 12:35 UTC, shimevaily commented on adapters/account/updateAccountElement.ts
> +  const res = await fetch(API_ROUTES.ACCOUNTS_ELEMENTS() + `/${String(elementId)}`, {
same here

2023-01-19 12:38 UTC, shimevaily commented on components/pages/AccountPage/ElementLine.tsx
> +    const values = getValues();
change this approach to values function props if possible. if not please respond

2023-01-19 12:38 UTC, shimevaily commented on components/pages/AccountPage/ElementLineCreate.tsx
> +    const values = getValues();
change this approach to values function props if possible. if not please respond

2023-01-19 13:01 UTC, shimevaily commented on components/pages/Accounts/DrawerContent.tsx
> +              <List component="div" disablePadding key={account.id}>
is this key necessary if we have one already on parent component?

2023-01-19 13:02 UTC, shimevaily commented on contexts/konva/provider.tsx
> +      console.log(accountId, dragTo, cancelDragCb, displayCaughtError);
for future investigation? 😁

2023-01-19 13:03 UTC, shimevaily commented on forms/createAccountElement.ts
> +  type: zodEnum([
maybe we should store this array somewhere else as const variable with unique name?

2023-01-19 13:04 UTC, shimevaily commented on interfaces/accountElement.ts
> +export enum ElementType {
is it okay to store enum in interfaces folder?

2023-01-19 13:07 UTC, shimevaily requested changes
.

2023-01-20 13:40 UTC, MizhgunMenk commented on contexts/konva/provider.tsx
> +      console.log(accountId, dragTo, cancelDragCb, displayCaughtError);
yes =)

2023-01-23 09:33 UTC, shimevaily approved these changes

2023-01-23 09:47 UTC, merged